create table if not exists public.story_section_rank_events (
  id bigint generated by default as identity primary key,
  event_date date not null default ((now() at time zone 'Asia/Phnom_Penh')::date),
  actor_key text not null,
  section_key text not null check (
    section_key in (
      'daily_picks',
      'trending_now',
      'update_today',
      'weekly_update',
      'new_arrivals',
      'ranking',
      'you_might_like'
    )
  ),
  story_id uuid not null references public.stories(id) on delete cascade,
  action text not null check (action in ('view', 'read')),
  created_at timestamptz not null default now(),
  constraint story_section_rank_events_unique
    unique (event_date, actor_key, section_key, story_id, action)
);

create index if not exists story_section_rank_events_date_idx
  on public.story_section_rank_events (event_date desc);

create index if not exists story_section_rank_events_section_idx
  on public.story_section_rank_events (event_date, section_key, action);

create index if not exists story_section_rank_events_story_idx
  on public.story_section_rank_events (story_id, event_date desc);

alter table public.story_section_rank_events enable row level security;
