begin;

create table if not exists public.author_hashtags (
  id bigint generated by default as identity primary key,
  tag_key text not null unique,
  tag text not null,
  usage_count bigint not null default 0 check (usage_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists author_hashtags_prefix_idx
  on public.author_hashtags (tag_key text_pattern_ops, usage_count desc);

create table if not exists public.author_post_hashtags (
  post_id uuid not null references public.author_page_posts(id) on delete cascade,
  hashtag_id bigint not null references public.author_hashtags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, hashtag_id)
);

create index if not exists author_post_hashtags_hashtag_idx
  on public.author_post_hashtags (hashtag_id);

create or replace function public.update_author_hashtag_usage_count()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    update public.author_hashtags
    set usage_count = usage_count + 1,
        updated_at = now()
    where id = new.hashtag_id;
    return new;
  end if;

  update public.author_hashtags
  set usage_count = greatest(usage_count - 1, 0),
      updated_at = now()
  where id = old.hashtag_id;

  return old;
end;
$$;

drop trigger if exists author_post_hashtags_usage_count_trigger
  on public.author_post_hashtags;

create trigger author_post_hashtags_usage_count_trigger
after insert or delete on public.author_post_hashtags
for each row
execute function public.update_author_hashtag_usage_count();

alter table public.author_hashtags enable row level security;
alter table public.author_post_hashtags enable row level security;

commit;
