BEGIN;

CREATE TABLE IF NOT EXISTS shadow_advertisement_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  placement text NOT NULL CHECK (placement IN ('opening', 'freeUnlock', 'me')),
  name text NOT NULL DEFAULT 'Untitled Ad',
  enabled boolean NOT NULL DEFAULT true,
  image_url text NOT NULL DEFAULT '',
  link_url text NOT NULL DEFAULT '',
  badge text NOT NULL DEFAULT '',
  duration_seconds integer NOT NULL DEFAULT 5 CHECK (duration_seconds >= 0),
  close_after_seconds integer NOT NULL DEFAULT 3 CHECK (close_after_seconds >= 0),
  frequency text NOT NULL DEFAULT 'once_per_session' CHECK (frequency IN ('once_per_session', 'once_per_day', 'every_visit', 'every_unlock')),
  sort_order integer NOT NULL DEFAULT 1 CHECK (sort_order >= 1),
  in_loop boolean NOT NULL DEFAULT false,
  is_archived boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (placement, id)
);

CREATE TABLE IF NOT EXISTS shadow_advertisement_rotation_settings (
  placement text PRIMARY KEY CHECK (placement IN ('opening', 'freeUnlock', 'me')),
  enabled boolean NOT NULL DEFAULT false,
  mode text NOT NULL DEFAULT 'manual' CHECK (mode IN ('manual', 'auto')),
  manual_ad_id bigint,
  rotate_every_seconds integer NOT NULL DEFAULT 3600 CHECK (rotate_every_seconds > 0),
  max_ads integer NOT NULL DEFAULT 1 CHECK (max_ads > 0),
  rotation_started_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT shadow_advertisement_rotation_manual_ad_fk
    FOREIGN KEY (placement, manual_ad_id)
    REFERENCES shadow_advertisement_items (placement, id)
);

CREATE INDEX IF NOT EXISTS shadow_advertisement_items_placement_order_idx
  ON shadow_advertisement_items (placement, is_archived, sort_order, id);

CREATE INDEX IF NOT EXISTS shadow_advertisement_items_loop_idx
  ON shadow_advertisement_items (placement, sort_order, id)
  WHERE in_loop = true AND enabled = true AND is_archived = false;

CREATE OR REPLACE FUNCTION shadow_touch_advertisement_rotation_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS shadow_advertisement_items_touch_updated_at ON shadow_advertisement_items;
CREATE TRIGGER shadow_advertisement_items_touch_updated_at
BEFORE UPDATE ON shadow_advertisement_items
FOR EACH ROW
EXECUTE FUNCTION shadow_touch_advertisement_rotation_updated_at();

DROP TRIGGER IF EXISTS shadow_advertisement_rotation_settings_touch_updated_at ON shadow_advertisement_rotation_settings;
CREATE TRIGGER shadow_advertisement_rotation_settings_touch_updated_at
BEFORE UPDATE ON shadow_advertisement_rotation_settings
FOR EACH ROW
EXECUTE FUNCTION shadow_touch_advertisement_rotation_updated_at();

INSERT INTO shadow_advertisement_items (
  placement,
  name,
  enabled,
  image_url,
  link_url,
  badge,
  duration_seconds,
  close_after_seconds,
  frequency,
  sort_order,
  in_loop,
  is_archived,
  created_at,
  updated_at
)
SELECT
  'opening',
  'Opening Ad 1',
  true,
  COALESCE(image_url, ''),
  COALESCE(link_url, ''),
  COALESCE(badge, ''),
  COALESCE(duration_seconds, 5),
  COALESCE(close_after_seconds, 3),
  COALESCE(frequency, 'once_per_session'),
  1,
  true,
  false,
  COALESCE(created_at, now()),
  COALESCE(updated_at, now())
FROM shadow_advertisements
WHERE placement = 'opening'
  AND NOT EXISTS (
    SELECT 1
    FROM shadow_advertisement_items
    WHERE placement = 'opening'
  )
LIMIT 1;

INSERT INTO shadow_advertisement_rotation_settings (
  placement,
  enabled,
  mode,
  manual_ad_id,
  rotate_every_seconds,
  max_ads,
  rotation_started_at,
  created_at,
  updated_at
)
SELECT
  'opening',
  COALESCE((
    SELECT enabled
    FROM shadow_advertisements
    WHERE placement = 'opening'
    LIMIT 1
  ), false),
  'manual',
  (
    SELECT id
    FROM shadow_advertisement_items
    WHERE placement = 'opening' AND is_archived = false
    ORDER BY sort_order ASC, id ASC
    LIMIT 1
  ),
  3600,
  1,
  now(),
  now(),
  now()
ON CONFLICT (placement) DO NOTHING;

COMMIT;
