create table if not exists public.search_term_groups (
  id bigint generated by default as identity primary key,
  canonical_term text not null,
  normalized_term text not null unique,
  status text not null default 'active'
    check (status in ('active', 'ignored', 'merged')),
  merged_into bigint references public.search_term_groups(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.search_term_aliases (
  normalized_alias text primary key,
  display_alias text not null,
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists public.search_analytics_daily (
  search_date date not null default current_date,
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  search_type text not null default 'all'
    check (search_type in ('all', 'readers', 'pages', 'stories', 'pdfs', 'posts')),
  searches integer not null default 0 check (searches >= 0),
  unique_searchers integer not null default 0 check (unique_searchers >= 0),
  no_result_searches integer not null default 0 check (no_result_searches >= 0),
  clicks integer not null default 0 check (clicks >= 0),
  result_count_total bigint not null default 0 check (result_count_total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (search_date, group_id, search_type)
);

create table if not exists public.search_term_variants_daily (
  search_date date not null default current_date,
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  search_type text not null default 'all'
    check (search_type in ('all', 'readers', 'pages', 'stories', 'pdfs', 'posts')),
  normalized_term text not null,
  display_term text not null,
  searches integer not null default 0 check (searches >= 0),
  no_result_searches integer not null default 0 check (no_result_searches >= 0),
  last_seen_at timestamptz not null default now(),
  primary key (search_date, group_id, search_type, normalized_term)
);

create table if not exists public.search_analytics_unique_daily (
  search_date date not null default current_date,
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  search_type text not null default 'all'
    check (search_type in ('all', 'readers', 'pages', 'stories', 'pdfs', 'posts')),
  searcher_hash text not null,
  created_at timestamptz not null default now(),
  primary key (search_date, group_id, search_type, searcher_hash)
);

create table if not exists public.search_analytics_recent_dedupe (
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  search_type text not null default 'all'
    check (search_type in ('all', 'readers', 'pages', 'stories', 'pdfs', 'posts')),
  searcher_hash text not null,
  last_searched_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '20 minutes'),
  primary key (group_id, search_type, searcher_hash)
);

create index if not exists idx_search_groups_status
  on public.search_term_groups(status);

create index if not exists idx_search_groups_merged_into
  on public.search_term_groups(merged_into);

create index if not exists idx_search_aliases_group
  on public.search_term_aliases(group_id);

create index if not exists idx_search_daily_group_date
  on public.search_analytics_daily(group_id, search_date desc);

create index if not exists idx_search_daily_date_type
  on public.search_analytics_daily(search_date desc, search_type);

create index if not exists idx_search_variants_group_date
  on public.search_term_variants_daily(group_id, search_date desc);

create index if not exists idx_search_unique_date
  on public.search_analytics_unique_daily(search_date);

create index if not exists idx_search_recent_expires
  on public.search_analytics_recent_dedupe(expires_at);

alter table public.search_term_groups enable row level security;
alter table public.search_term_aliases enable row level security;
alter table public.search_analytics_daily enable row level security;
alter table public.search_term_variants_daily enable row level security;
alter table public.search_analytics_unique_daily enable row level security;
alter table public.search_analytics_recent_dedupe enable row level security;

revoke all on table public.search_term_groups from anon, authenticated;
revoke all on table public.search_term_aliases from anon, authenticated;
revoke all on table public.search_analytics_daily from anon, authenticated;
revoke all on table public.search_term_variants_daily from anon, authenticated;
revoke all on table public.search_analytics_unique_daily from anon, authenticated;
revoke all on table public.search_analytics_recent_dedupe from anon, authenticated;

grant all on table public.search_term_groups to service_role;
grant all on table public.search_term_aliases to service_role;
grant all on table public.search_analytics_daily to service_role;
grant all on table public.search_term_variants_daily to service_role;
grant all on table public.search_analytics_unique_daily to service_role;
grant all on table public.search_analytics_recent_dedupe to service_role;

grant usage, select on all sequences in schema public to service_role;

create or replace function public.purge_search_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cutoff date := current_date - 90;
  v_daily integer := 0;
  v_variants integer := 0;
  v_unique integer := 0;
  v_recent integer := 0;
begin
  delete from public.search_analytics_daily
  where search_date < v_cutoff;
  get diagnostics v_daily = row_count;

  delete from public.search_term_variants_daily
  where search_date < v_cutoff;
  get diagnostics v_variants = row_count;

  delete from public.search_analytics_unique_daily
  where search_date < v_cutoff;
  get diagnostics v_unique = row_count;

  delete from public.search_analytics_recent_dedupe
  where expires_at <= now();
  get diagnostics v_recent = row_count;

  return jsonb_build_object(
    'cutoff_date', v_cutoff,
    'daily_deleted', v_daily,
    'variants_deleted', v_variants,
    'unique_deleted', v_unique,
    'dedupe_deleted', v_recent
  );
end;
$$;

revoke all
on function public.purge_search_analytics()
from public, anon, authenticated;

grant execute
on function public.purge_search_analytics()
to service_role;
