create table if not exists public.search_analytics_recent_activity (
  id bigint generated by default as identity primary key,
  group_id bigint not null
    references public.search_term_groups(id) on delete cascade,
  search_type text not null default 'all'
    check (
      search_type in (
        'all',
        'readers',
        'pages',
        'stories',
        'pdfs',
        'posts'
      )
    ),
  normalized_term text not null,
  display_term text not null,
  searcher_hash text not null,
  reader_id text,
  result_count integer not null default 0
    check (result_count >= 0),
  searched_at timestamptz not null default now()
);

create table if not exists public.search_analytics_maintenance (
  maintenance_key text primary key,
  last_run_at timestamptz not null
);

insert into public.search_analytics_maintenance (
  maintenance_key,
  last_run_at
)
values (
  'purge',
  '1970-01-01 00:00:00+00'::timestamptz
)
on conflict (maintenance_key) do nothing;

create index if not exists idx_search_activity_searched_at
  on public.search_analytics_recent_activity(searched_at desc);

create index if not exists idx_search_activity_reader
  on public.search_analytics_recent_activity(reader_id, searched_at desc);

create index if not exists idx_search_activity_group
  on public.search_analytics_recent_activity(group_id, searched_at desc);

alter table public.search_analytics_recent_activity
  enable row level security;

alter table public.search_analytics_maintenance
  enable row level security;

revoke all
on table public.search_analytics_recent_activity
from anon, authenticated;

revoke all
on table public.search_analytics_maintenance
from anon, authenticated;

grant all
on table public.search_analytics_recent_activity
to service_role;

grant all
on table public.search_analytics_maintenance
to service_role;

grant usage, select
on all sequences in schema public
to service_role;

create or replace function public.purge_search_analytics()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cutoff date := current_date - 90;
  v_activity_cutoff timestamptz :=
    now() - interval '90 days';
  v_daily integer := 0;
  v_variants integer := 0;
  v_unique integer := 0;
  v_recent integer := 0;
  v_click_recent integer := 0;
  v_activity integer := 0;
begin
  delete from public.search_analytics_daily
  where search_date < v_cutoff;
  get diagnostics v_daily = row_count;

  delete from public.search_term_variants_daily
  where search_date < v_cutoff;
  get diagnostics v_variants = row_count;

  delete from public.search_analytics_unique_daily
  where search_date < v_cutoff;
  get diagnostics v_unique = row_count;

  delete from public.search_analytics_recent_dedupe
  where expires_at <= now();
  get diagnostics v_recent = row_count;

  delete from public.search_analytics_click_dedupe
  where expires_at <= now();
  get diagnostics v_click_recent = row_count;

  delete from public.search_analytics_recent_activity
  where searched_at < v_activity_cutoff;
  get diagnostics v_activity = row_count;

  return jsonb_build_object(
    'cutoff_date',
    v_cutoff,
    'daily_deleted',
    v_daily,
    'variants_deleted',
    v_variants,
    'unique_deleted',
    v_unique,
    'dedupe_deleted',
    v_recent,
    'click_dedupe_deleted',
    v_click_recent,
    'activity_deleted',
    v_activity
  );
end;
$$;

revoke all
on function public.purge_search_analytics()
from public, anon, authenticated;

grant execute
on function public.purge_search_analytics()
to service_role;

create or replace function public.record_search_analytics_event(
  p_display_term text,
  p_normalized_term text,
  p_search_type text,
  p_searcher_hash text,
  p_result_count integer,
  p_reader_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_today date := current_date;
  v_group_id bigint;
  v_redirect_group_id bigint;
  v_group_status text;
  v_counted_group_id bigint;
  v_unique_added integer := 0;
  v_no_result integer := 0;
  v_result_count integer :=
    least(
      1000,
      greatest(coalesce(p_result_count, 0), 0)
    );
  v_display_term text :=
    left(trim(coalesce(p_display_term, '')), 120);
  v_normalized_term text :=
    left(
      lower(trim(coalesce(p_normalized_term, ''))),
      120
    );
  v_search_type text :=
    lower(trim(coalesce(p_search_type, 'all')));
  v_reader_id text :=
    nullif(left(trim(coalesce(p_reader_id, '')), 160), '');
  v_maintenance_key text;
begin
  if length(v_normalized_term) < 2 then
    return jsonb_build_object(
      'ok',
      true,
      'counted',
      false,
      'reason',
      'term_too_short'
    );
  end if;

  if length(trim(coalesce(p_searcher_hash, ''))) < 16 then
    return jsonb_build_object(
      'ok',
      true,
      'counted',
      false,
      'reason',
      'missing_searcher'
    );
  end if;

  if v_search_type not in (
    'all',
    'readers',
    'pages',
    'stories',
    'pdfs',
    'posts'
  ) then
    v_search_type := 'all';
  end if;

  select a.group_id
  into v_group_id
  from public.search_term_aliases a
  where a.normalized_alias = v_normalized_term
  limit 1;

  if v_group_id is null then
    insert into public.search_term_groups (
      canonical_term,
      normalized_term,
      status,
      created_at,
      updated_at
    )
    values (
      coalesce(
        nullif(v_display_term, ''),
        v_normalized_term
      ),
      v_normalized_term,
      'active',
      v_now,
      v_now
    )
    on conflict (normalized_term)
    do update set
      updated_at = excluded.updated_at
    returning id
    into v_group_id;
  end if;

  select
    status,
    merged_into
  into
    v_group_status,
    v_redirect_group_id
  from public.search_term_groups
  where id = v_group_id;

  if v_group_status = 'ignored' then
    return jsonb_build_object(
      'ok',
      true,
      'counted',
      false,
      'reason',
      'ignored_group',
      'group_id',
      v_group_id
    );
  end if;

  if (
    v_group_status = 'merged' and
    v_redirect_group_id is not null
  ) then
    v_group_id := v_redirect_group_id;
  end if;

  insert into public.search_term_aliases (
    normalized_alias,
    display_alias,
    group_id,
    created_at,
    last_seen_at
  )
  values (
    v_normalized_term,
    coalesce(
      nullif(v_display_term, ''),
      v_normalized_term
    ),
    v_group_id,
    v_now,
    v_now
  )
  on conflict (normalized_alias)
  do update set
    display_alias = excluded.display_alias,
    group_id = excluded.group_id,
    last_seen_at = excluded.last_seen_at;

  v_counted_group_id := null;

  insert into public.search_analytics_recent_dedupe (
    group_id,
    search_type,
    searcher_hash,
    last_searched_at,
    expires_at
  )
  values (
    v_group_id,
    v_search_type,
    p_searcher_hash,
    v_now,
    v_now + interval '30 minutes'
  )
  on conflict (
    group_id,
    search_type,
    searcher_hash
  )
  do update set
    last_searched_at = excluded.last_searched_at,
    expires_at = excluded.expires_at
  where
    public.search_analytics_recent_dedupe.expires_at <=
      v_now
  returning group_id
  into v_counted_group_id;

  if v_counted_group_id is null then
    return jsonb_build_object(
      'ok',
      true,
      'counted',
      false,
      'reason',
      'recent_duplicate',
      'group_id',
      v_group_id
    );
  end if;

  insert into public.search_analytics_unique_daily (
    search_date,
    group_id,
    search_type,
    searcher_hash,
    created_at
  )
  values (
    v_today,
    v_group_id,
    v_search_type,
    p_searcher_hash,
    v_now
  )
  on conflict do nothing;

  get diagnostics v_unique_added = row_count;

  if v_result_count = 0 then
    v_no_result := 1;
  end if;

  insert into public.search_analytics_daily (
    search_date,
    group_id,
    search_type,
    searches,
    unique_searchers,
    no_result_searches,
    clicks,
    result_count_total,
    created_at,
    updated_at
  )
  values (
    v_today,
    v_group_id,
    v_search_type,
    1,
    v_unique_added,
    v_no_result,
    0,
    v_result_count,
    v_now,
    v_now
  )
  on conflict (
    search_date,
    group_id,
    search_type
  )
  do update set
    searches =
      public.search_analytics_daily.searches + 1,
    unique_searchers =
      public.search_analytics_daily.unique_searchers +
      excluded.unique_searchers,
    no_result_searches =
      public.search_analytics_daily.no_result_searches +
      excluded.no_result_searches,
    result_count_total =
      public.search_analytics_daily.result_count_total +
      excluded.result_count_total,
    updated_at = excluded.updated_at;

  insert into public.search_term_variants_daily (
    search_date,
    group_id,
    search_type,
    normalized_term,
    display_term,
    searches,
    no_result_searches,
    last_seen_at
  )
  values (
    v_today,
    v_group_id,
    v_search_type,
    v_normalized_term,
    coalesce(
      nullif(v_display_term, ''),
      v_normalized_term
    ),
    1,
    v_no_result,
    v_now
  )
  on conflict (
    search_date,
    group_id,
    search_type,
    normalized_term
  )
  do update set
    display_term = excluded.display_term,
    searches =
      public.search_term_variants_daily.searches + 1,
    no_result_searches =
      public.search_term_variants_daily.no_result_searches +
      excluded.no_result_searches,
    last_seen_at = excluded.last_seen_at;

  insert into public.search_analytics_recent_activity (
    group_id,
    search_type,
    normalized_term,
    display_term,
    searcher_hash,
    reader_id,
    result_count,
    searched_at
  )
  values (
    v_group_id,
    v_search_type,
    v_normalized_term,
    coalesce(
      nullif(v_display_term, ''),
      v_normalized_term
    ),
    p_searcher_hash,
    v_reader_id,
    v_result_count,
    v_now
  );

  update public.search_analytics_maintenance
  set last_run_at = v_now
  where maintenance_key = 'purge'
    and last_run_at <= v_now - interval '24 hours'
  returning maintenance_key
  into v_maintenance_key;

  if v_maintenance_key is not null then
    perform public.purge_search_analytics();
  end if;

  return jsonb_build_object(
    'ok',
    true,
    'counted',
    true,
    'group_id',
    v_group_id,
    'unique_added',
    v_unique_added = 1,
    'no_result',
    v_no_result = 1
  );
end;
$$;

revoke all
on function public.record_search_analytics_event(
  text,
  text,
  text,
  text,
  integer,
  text
)
from public, anon, authenticated;

grant execute
on function public.record_search_analytics_event(
  text,
  text,
  text,
  text,
  integer,
  text
)
to service_role;

create or replace function public.record_search_analytics_click(
  p_normalized_term text,
  p_search_type text,
  p_searcher_hash text,
  p_target_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_now timestamptz := now();
  v_today date := current_date;
  v_group_id bigint;
  v_redirect_group_id bigint;
  v_group_status text;
  v_counted_group_id bigint;
  v_normalized_term text :=
    left(
      lower(trim(coalesce(p_normalized_term, ''))),
      120
    );
  v_search_type text :=
    lower(trim(coalesce(p_search_type, 'all')));
  v_target_key text :=
    left(trim(coalesce(p_target_key, '')), 220);
begin
  if length(v_normalized_term) < 2 then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'term_too_short'
    );
  end if;

  if length(trim(coalesce(p_searcher_hash, ''))) < 16 then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'missing_searcher'
    );
  end if;

  if length(v_target_key) < 3 then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'missing_target'
    );
  end if;

  if v_search_type not in (
    'all',
    'readers',
    'pages',
    'stories',
    'pdfs',
    'posts'
  ) then
    v_search_type := 'all';
  end if;

  select a.group_id
  into v_group_id
  from public.search_term_aliases a
  where a.normalized_alias = v_normalized_term
  limit 1;

  if v_group_id is null then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'group_not_found'
    );
  end if;

  select
    g.status,
    g.merged_into
  into
    v_group_status,
    v_redirect_group_id
  from public.search_term_groups g
  where g.id = v_group_id;

  if v_group_status = 'ignored' then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'ignored_group',
      'group_id',
      v_group_id
    );
  end if;

  if (
    v_group_status = 'merged' and
    v_redirect_group_id is not null
  ) then
    v_group_id := v_redirect_group_id;
  end if;

  if not exists (
    select 1
    from public.search_analytics_recent_dedupe d
    where d.group_id = v_group_id
      and d.search_type = v_search_type
      and d.searcher_hash = p_searcher_hash
      and d.expires_at > v_now
      and d.last_searched_at >=
        date_trunc('day', v_now)
  ) then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'no_recent_search',
      'group_id',
      v_group_id
    );
  end if;

  if exists (
    select 1
    from public.search_analytics_click_dedupe c
    where c.group_id = v_group_id
      and c.search_type = v_search_type
      and c.searcher_hash = p_searcher_hash
      and c.expires_at > v_now
  ) then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'recent_duplicate',
      'group_id',
      v_group_id
    );
  end if;

  v_counted_group_id := null;

  insert into public.search_analytics_click_dedupe (
    group_id,
    search_type,
    searcher_hash,
    target_key,
    last_clicked_at,
    expires_at
  )
  values (
    v_group_id,
    v_search_type,
    p_searcher_hash,
    v_target_key,
    v_now,
    v_now + interval '30 minutes'
  )
  on conflict (
    group_id,
    search_type,
    searcher_hash,
    target_key
  )
  do update set
    last_clicked_at = excluded.last_clicked_at,
    expires_at = excluded.expires_at
  where
    public.search_analytics_click_dedupe.expires_at <=
      v_now
  returning group_id
  into v_counted_group_id;

  if v_counted_group_id is null then
    return jsonb_build_object(
      'counted',
      false,
      'reason',
      'recent_duplicate',
      'group_id',
      v_group_id
    );
  end if;

  insert into public.search_analytics_daily (
    search_date,
    group_id,
    search_type,
    searches,
    unique_searchers,
    no_result_searches,
    clicks,
    result_count_total,
    created_at,
    updated_at
  )
  values (
    v_today,
    v_group_id,
    v_search_type,
    0,
    0,
    0,
    1,
    0,
    v_now,
    v_now
  )
  on conflict (
    search_date,
    group_id,
    search_type
  )
  do update set
    clicks =
      public.search_analytics_daily.clicks + 1,
    updated_at = excluded.updated_at;

  return jsonb_build_object(
    'counted',
    true,
    'group_id',
    v_group_id
  );
end;
$$;

revoke all
on function public.record_search_analytics_click(
  text,
  text,
  text,
  text
)
from public, anon, authenticated;

grant execute
on function public.record_search_analytics_click(
  text,
  text,
  text,
  text
)
to service_role;
