create table if not exists public.story_like_history (
  id bigint generated by default as identity primary key,
  story_id uuid not null references public.stories(id) on delete cascade,
  old_total_likes bigint not null default 0,
  new_total_likes bigint not null default 0,
  changed_at timestamptz not null default now(),
  changed_by text not null default session_user,
  transaction_id bigint not null default txid_current()
);

create index if not exists story_like_history_story_changed_idx
on public.story_like_history (story_id, changed_at desc);

create or replace function public.log_story_total_likes_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(old.total_likes, 0) is distinct from coalesce(new.total_likes, 0) then
    insert into public.story_like_history (
      story_id,
      old_total_likes,
      new_total_likes,
      changed_at,
      changed_by,
      transaction_id
    )
    values (
      new.id,
      coalesce(old.total_likes, 0),
      coalesce(new.total_likes, 0),
      now(),
      session_user,
      txid_current()
    );
  end if;

  return new;
end;
$$;

drop trigger if exists story_total_likes_history_trigger
on public.stories;

create trigger story_total_likes_history_trigger
after update of total_likes
on public.stories
for each row
execute function public.log_story_total_likes_change();

alter table public.story_like_history
enable row level security;

revoke all on public.story_like_history
from public, anon, authenticated;

grant select, insert on public.story_like_history
to service_role;
