create table if not exists public.system_usage_incidents (
  id bigint generated by default as identity primary key,
  fingerprint text not null,
  status text not null default 'OPEN',
  severity text not null default 'medium',
  feature text not null default 'unknown',
  source_route text not null default 'UNKNOWN',
  dependency text not null default 'UNKNOWN',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  delete_after timestamptz,
  recurrence_count integer not null default 0,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint system_usage_incidents_status_check
    check (status in ('OPEN', 'INVESTIGATING', 'RESOLVED')),
  constraint system_usage_incidents_recurrence_check
    check (recurrence_count >= 0)
);

create index if not exists system_usage_incidents_status_idx
  on public.system_usage_incidents (status, last_seen_at desc);

create index if not exists system_usage_incidents_fingerprint_idx
  on public.system_usage_incidents (fingerprint, last_seen_at desc);

create index if not exists system_usage_incidents_cleanup_idx
  on public.system_usage_incidents (delete_after)
  where status = 'RESOLVED';

create or replace function public.touch_system_usage_incident_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_system_usage_incidents_updated_at
  on public.system_usage_incidents;

create trigger trg_system_usage_incidents_updated_at
before update on public.system_usage_incidents
for each row
execute function public.touch_system_usage_incident_updated_at();

alter table public.system_usage_incidents enable row level security;
