create table if not exists public.system_usage_snapshots (
  id bigint generated by default as identity primary key,
  window_start timestamptz not null,
  window_end timestamptz not null,
  request_count bigint not null default 0,
  bytes bigint not null default 0,
  errors bigint not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint system_usage_snapshots_window_unique
    unique (window_start, window_end),
  constraint system_usage_snapshots_window_order
    check (window_end > window_start)
);

create index if not exists system_usage_snapshots_window_end_idx
  on public.system_usage_snapshots (window_end desc);

alter table public.system_usage_snapshots enable row level security;
