create table if not exists public.system_usage_rollups (
  id bigint generated by default as identity primary key,
  granularity text not null,
  bucket_start timestamptz not null,
  bucket_end timestamptz not null,
  request_count bigint not null default 0,
  bytes bigint not null default 0,
  errors bigint not null default 0,
  source_rows integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint system_usage_rollups_granularity_check
    check (granularity in ('hour', 'day', 'month')),
  constraint system_usage_rollups_bucket_order
    check (bucket_end > bucket_start),
  constraint system_usage_rollups_source_rows_check
    check (source_rows >= 0),
  constraint system_usage_rollups_unique
    unique (granularity, bucket_start, bucket_end)
);

create index if not exists system_usage_rollups_lookup_idx
  on public.system_usage_rollups
  (granularity, bucket_start, bucket_end);

create index if not exists system_usage_rollups_bucket_end_idx
  on public.system_usage_rollups
  (granularity, bucket_end desc);

create or replace function public.touch_system_usage_rollup_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_system_usage_rollups_updated_at
  on public.system_usage_rollups;

create trigger trg_system_usage_rollups_updated_at
before update on public.system_usage_rollups
for each row
execute function public.touch_system_usage_rollup_updated_at();

alter table public.system_usage_rollups enable row level security;
