ALTER TABLE public.task_center_settings
  ADD COLUMN IF NOT EXISTS reading_mission_mode text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS auto_last_rotation_date date,
  ADD COLUMN IF NOT EXISTS auto_last_rotated_at timestamptz;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'task_center_settings_reading_mission_mode_check'
      AND conrelid = 'public.task_center_settings'::regclass
  ) THEN
    ALTER TABLE public.task_center_settings
      ADD CONSTRAINT task_center_settings_reading_mission_mode_check
      CHECK (reading_mission_mode IN ('manual', 'auto'));
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.task_center_auto_story_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  featured_date date NOT NULL,
  slot smallint NOT NULL CHECK (slot IN (1, 2)),
  story_id text NOT NULL,
  mission_id text,
  selection_source text NOT NULL CHECK (
    selection_source IN ('unseen', 'updated', 'new', 'completed', 'recycle')
  ),
  story_status text,
  story_updated_at timestamptz,
  selected_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS task_center_auto_story_history_date_slot_uidx
  ON public.task_center_auto_story_history (featured_date, slot);

CREATE UNIQUE INDEX IF NOT EXISTS task_center_auto_story_history_date_story_uidx
  ON public.task_center_auto_story_history (featured_date, story_id);

CREATE INDEX IF NOT EXISTS task_center_auto_story_history_story_selected_idx
  ON public.task_center_auto_story_history (story_id, selected_at DESC);

CREATE INDEX IF NOT EXISTS task_center_auto_story_history_featured_date_idx
  ON public.task_center_auto_story_history (featured_date DESC);

ALTER TABLE public.task_center_auto_story_history ENABLE ROW LEVEL SECURITY;
